/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2023-03-11 05:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;

public final class instruction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Deepak%20Parashar/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("file:/C:/Users/Deepak%20Parashar/.m2/repository/org/springframework/spring-webmvc/5.1.3.RELEASE/spring-webmvc-5.1.3.RELEASE.jar", Long.valueOf(1588329221019L));
    _jspx_dependants.put("file:/C:/Users/Deepak%20Parashar/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1592300692560L));
    _jspx_dependants.put("jar:file:/C:/Users/Deepak%20Parashar/.m2/repository/org/springframework/spring-webmvc/5.1.3.RELEASE/spring-webmvc-5.1.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1543290104000L));
    _jspx_dependants.put("jar:file:/C:/Users/Deepak%20Parashar/.m2/repository/org/springframework/spring-webmvc/5.1.3.RELEASE/spring-webmvc-5.1.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1543290104000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("  \r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"\" href=\"css/bootstrap.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome CDN -->\r\n");
      out.write("    <!-- <script src=\"https://kit.fontawesome.com/23412c6a8d.js\"></script> -->\r\n");
      out.write("    <script src=\"js/fontawesome.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- css file cdn -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/loginAzadi.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery cdn -->\r\n");
      out.write("   <!-- DataTables script -->\r\n");
      out.write("\r\n");
      out.write("\t<Script src=\"js/jquery-3.5.1.min.js\"></Script>\r\n");
      out.write("    <Script src=\"js/jquery.validate.min.js\"></Script>\r\n");
      out.write("    <Script src=\"js/bootstrap.min.js\"></Script>\r\n");
      out.write("    <!-- js file link -->\r\n");
      out.write("    <script  type=\"text/javascript\" src=\"js/style.js\"></script>\r\n");
      out.write("    <script  src=\"js/bootstrap-password-toggler.min.js\"></script>   \r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <title>Azadi ka Amrit Mahotsav Program System</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("       .container-fluid{\r\n");
      out.write("          background-image: url(../images/Background_main.jpg);\r\n");
      out.write("       }\r\n");
      out.write("       .sub_btn_azadi .btn-blue{\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t/*background-color: #fff;\r\n");
      out.write("\t\t\tz-index: 1;\r\n");
      out.write("\t\t\tcolor: #fff;*/\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*.sub_btn_azadi .btn-blue::before{\r\n");
      out.write("\t\t   content: '';\r\n");
      out.write("\t\t   position: absolute;\r\n");
      out.write("\t\t   left: 0;\r\n");
      out.write("\t\t   top: 0;\r\n");
      out.write("\t\t   width:100%;\r\n");
      out.write("\t\t   height: 100%;\r\n");
      out.write("\t\t   border: 2px solid #1A237E;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.sub_btn_azadi .btn-blue::after{\r\n");
      out.write("\t\t   content: '';\r\n");
      out.write("\t\t   position: absolute;\r\n");
      out.write("\t\t   top: 50%;\r\n");
      out.write("\t\t   left: 50%;\r\n");
      out.write("\t\t   transform: translate(-50%, -50%);\r\n");
      out.write("\t\t   width: 95%;\r\n");
      out.write("\t\t   height: 80%;\r\n");
      out.write("\t\t   background-color: #1A237E;\r\n");
      out.write("\t\t   border-radius: 5px;\r\n");
      out.write("\t\t   z-index: -1;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.loginBy_col .card2{\r\n");
      out.write("\t\t    width: 90%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@media only screen and (max-width: 1024px){\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("function forgetPassword()\r\n");
      out.write("{\r\n");
      out.write("\t \r\n");
      out.write("     var loginId =  document.getElementById(\"loginId\").value;\r\n");
      out.write("     \r\n");
      out.write("     if (loginId ==\"\") {\r\n");
      out.write("    \t //alert (\"loginId is mandatory\")\r\n");
      out.write("    \tswal({\r\n");
      out.write("\t\t\t  //title: \"Good job!\",\r\n");
      out.write("\t\t\t  text: \"Please fill Login Id and captcha to get password\",\r\n");
      out.write("\t\t\t  icon: \"warning\",\r\n");
      out.write("\t\t\t  button: \"Ok\",\r\n");
      out.write("\t\t\t  //dangerMode: true\r\n");
      out.write("\t\t\t  closeOnClickOutside: false, // prevent close on click anywhere/outside\r\n");
      out.write("\t\t\t  showConfirmButton: false,\r\n");
      out.write("\t\t\t  allowOutsideClick: false,\r\n");
      out.write("\t\t\t  allowEscapeKey: false\r\n");
      out.write("\t\t });\r\n");
      out.write("    \t \r\n");
      out.write("\t\t\r\n");
      out.write("    \t return false;\r\n");
      out.write("    \t}\r\n");
      out.write("     \r\n");
      out.write("     var captcha =  document.getElementById(\"captcha\").value;\r\n");
      out.write("     if (captcha ==\"\") {\r\n");
      out.write("    \t //alert (\"captcha is mandatory\")\r\n");
      out.write("    \t swal({\r\n");
      out.write("\t\t\t  //title: \"Good job!\",\r\n");
      out.write("\t\t\t  text: \"Please fill captcha to get password\",\r\n");
      out.write("\t\t\t  icon: \"warning\",\r\n");
      out.write("\t\t\t  button: \"Ok\",\r\n");
      out.write("\t\t\t  //dangerMode: true\r\n");
      out.write("\t\t\t  closeOnClickOutside: false, // prevent close on click anywhere/outside\r\n");
      out.write("\t\t\t  showConfirmButton: false,\r\n");
      out.write("\t\t\t  allowOutsideClick: false,\r\n");
      out.write("\t\t\t  allowEscapeKey: false\r\n");
      out.write("\t\t });\r\n");
      out.write("    \t return false;\r\n");
      out.write("    \t}\r\n");
      out.write("     \r\n");
      out.write("  var loginRole =  document.getElementById(\"loginRole\").value;\r\n");
      out.write("     \r\n");
      out.write("     if (loginRole ==\"\") {\r\n");
      out.write("    \t //alert (\"loginId is mandatory\")\r\n");
      out.write("    \tswal({\r\n");
      out.write("\t\t\t  //title: \"Good job!\",\r\n");
      out.write("\t\t\t  text: \"Please fill Login As to get password\",\r\n");
      out.write("\t\t\t  icon: \"warning\",\r\n");
      out.write("\t\t\t  button: \"Ok\",\r\n");
      out.write("\t\t\t  //dangerMode: true\r\n");
      out.write("\t\t\t  closeOnClickOutside: false, // prevent close on click anywhere/outside\r\n");
      out.write("\t\t\t  showConfirmButton: false,\r\n");
      out.write("\t\t\t  allowOutsideClick: false,\r\n");
      out.write("\t\t\t  allowEscapeKey: false\r\n");
      out.write("\t\t });\r\n");
      out.write("    \t \r\n");
      out.write("\t\t\r\n");
      out.write("    \t return false;\r\n");
      out.write("    \t}\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("     $('#loginId1').val(loginId);\r\n");
      out.write("     $('#captcha1').val(captcha);\r\n");
      out.write("     $('#loginRole').val(loginRole);\r\n");
      out.write("     $('#Forgotform').submit();\r\n");
      out.write("    \t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function back_block() {\r\n");
      out.write("\t\r\n");
      out.write("window.history.foward(-1)\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("Response.ExpiresAbsolute = new Date();//DateTime.Now;\r\n");
      out.write("Response.Expires = 0;\r\n");
      out.write("Response.CacheControl = \"no-cache\";\r\n");
      out.write("</script>\r\n");
      out.write("  ");

response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", -1); //prevent caching at the proxy server

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <body  onload=\"loadaptcha();\">\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("  <div class=\"container-fluid px-1 px-md-2 px-lg-1 px-xl-2 py-2 m-auto instruction_page\">\r\n");
      out.write("    <div class=\"card card0 border-0\">\r\n");
      out.write("        <div class=\"row d-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 col-md-12\">\r\n");
      out.write("                <!-- <div class=\"card1 pb-5\"> -->\r\n");
      out.write("                    <!-- <div class=\"row\"> \r\n");
      out.write("                       <img src=\"images/logo.png\" class=\"logo\"> \r\n");
      out.write("                    </div> -->\r\n");
      out.write("                    <!-- <div class=\"row px-3 justify-content-center mt-4 mb-5 border-line\"> \r\n");
      out.write("                      <img src=\"images/azadi_mahotsav.png\" class=\"image\"> \r\n");
      out.write("                    </div>-->\r\n");
      out.write("                    <!-- <div class=\"login_text\">\r\n");
      out.write("                        <h3>Azadi Mahotsav</h3>\r\n");
      out.write("                        <p>We walked through fifty-two districts barefoot . We would tell the villagers about freedom</p>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("               <!--  </div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 col-md-12 loginBy_col\">\r\n");
      out.write("               <p class=\"nseMsg\">\r\n");
      out.write("\t\t\t              Helpline is available from Monday to Friday 9:30 AM till 5:30 PM <i>(Helpdesk will remain closed on public holidays).</i> Help line number - 8095210200\r\n");
      out.write("\t\t\t    </p>  \r\n");
      out.write("                <div class=\"card2 card border-0 px-2 py-3\">\r\n");
      out.write("                    <!--<div class=\"row mb-4 px-2\">-->\r\n");
      out.write("                        <!-- <h4 class=\"mb-0 mr-4 mt-2\">Sign In</h4> -->\r\n");
      out.write("                        <!-- <h4 class=\"mb-0 mr-4 \">\r\n");
      out.write("                           <span>Azadi Ka Amrit Mahotsav</span>\r\n");
      out.write("                           <br>Program System\r\n");
      out.write("                        </h4> -->\r\n");
      out.write("                        <!-- <div class=\"comp_logo\">\r\n");
      out.write("                           <img src=\"images/azadi_mahotsav.png\" class=\"image\">\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                       \r\n");
      out.write("                   <!--  </div> -->\r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-12 sub_btn sub_btn_azadi\">\r\n");
      out.write("                        <a href=\"loginAzadiQuiz\" class=\"card shadow\">\r\n");
      out.write("\t\t\t              <div class=\"card_icon\">\r\n");
      out.write("\t\t\t                <!-- <i class=\"fas fa-chalkboard-teacher\"></i> -->\r\n");
      out.write("\t\t\t                <img src=\"../images/quiz_icon.jpg\">\r\n");
      out.write("\t\t\t              </div> \r\n");
      out.write("\t\t\t              <div class=\"card-body\"> \r\n");
      out.write("\t\t\t                Apply For Quiz\r\n");
      out.write("\t\t\t              </div>  \r\n");
      out.write("\t\t\t           </a> \r\n");
      out.write("\t\t\t          \r\n");
      out.write("\t\t\t           <a href=\"loginAzadiEssay\" class=\"card shadow\">\r\n");
      out.write("\t\t\t              <div class=\"card_icon\">\r\n");
      out.write("\t\t\t                <!-- <i class=\"fas fa-chalkboard-teacher\"></i> -->\r\n");
      out.write("\t\t\t                <img src=\"../images/essay_icons.jpg\">\r\n");
      out.write("\t\t\t              </div> \r\n");
      out.write("\t\t\t              <div class=\"card-body\"> \r\n");
      out.write("\t\t\t                Apply For Essay\r\n");
      out.write("\t\t\t              </div>  \r\n");
      out.write("\t\t\t           </a> \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t             \r\n");
      out.write("                       <!--  <a href=\"loginAzadiQuiz\" class=\"btn btn-blue text-center\">Apply For Quiz</a>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <a href=\"loginAzadiEssay\" class=\"btn btn-blue text-center\">Apply For Essay</a> -->\r\n");
      out.write("                    </div> \r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                 \r\n");
      out.write("                 <!-- ==========hidden input========== -->\r\n");
      out.write("                  <form action=forgetPassword method=POST id=\"Forgotform\" name=\"Forgotform\">\r\n");
      out.write("                     \r\n");
      out.write("                      <input type=\"hidden\" name=\"loginId1\" id=\"loginId1\" class=\"form-input\" required>\r\n");
      out.write("                      <input type=\"hidden\" name=\"captcha1\" id=\"captcha1\" class=\"form-input\" required>\r\n");
      out.write("                      <input type=\"hidden\" name=\"loginFrom\" id=\"loginFrom\"  value=\"loginAzadi\"> \r\n");
      out.write("                      <input type=\"hidden\" name=\"loginRole\" id=\"loginRole\" >       \r\n");
      out.write("                     \r\n");
      out.write("                  </form>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-blue py-2\">\r\n");
      out.write("            <div class=\"row px-3\"> <small class=\"ml-4 ml-sm-5 mb-2\">Copyright &copy; <script>document.write(new Date().getFullYear());</script>. All rights reserved by <a href=\"https://www.nism.ac.in/\" target=\"_blank\">National Institute Of Securities Markets</a></small>\r\n");
      out.write("              <!--    <div class=\"social-contact ml-4 ml-sm-auto\"> <span class=\"fa fa-facebook mr-4 text-sm\"></span> <span class=\"fa fa-google-plus mr-4 text-sm\"></span> <span class=\"fa fa-linkedin mr-4 text-sm\"></span> <span class=\"fa fa-twitter mr-4 mr-sm-5 text-sm\"></span> </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write(" \r\n");
      out.write("\tfunction loadaptcha(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("            url: 'getAYTCaptcha',\r\n");
      out.write("            type: 'get',\r\n");
      out.write("            cache: false,\r\n");
      out.write("            //dataType: 'image/jpeg',\r\n");
      out.write("            //data: {action: 'process'},\r\n");
      out.write("            success: function(data){\r\n");
      out.write("        \t\tdocument.getElementById('randomText').innerHTML = data;\r\n");
      out.write("    \t\t}\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\"#reload\").click(function(){\r\n");
      out.write("        \t\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("                url: 'getAYTCaptcha',\r\n");
      out.write("                type: 'get',\r\n");
      out.write("                cache: false,\r\n");
      out.write("                //dataType: 'image/jpeg',\r\n");
      out.write("                //data: {action: 'process'},\r\n");
      out.write("                success: function(data){\r\n");
      out.write("            \t\tdocument.getElementById('randomText').innerHTML = data;\r\n");
      out.write("        \t\t}\r\n");
      out.write("            });\r\n");
      out.write("        \t\r\n");
      out.write("            //location.reload(true);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<script>\r\n");
      out.write("      // Example starter JavaScript for disabling form submissions if there are invalid fields\r\n");
      out.write("      (function() {\r\n");
      out.write("        'use strict';\r\n");
      out.write("        window.addEventListener('load', function() {\r\n");
      out.write("          // Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n");
      out.write("          var forms = document.getElementsByClassName('needs-validation');\r\n");
      out.write("          // Loop over them and prevent submission\r\n");
      out.write("          var validation = Array.prototype.filter.call(forms, function(form) {\r\n");
      out.write("            form.addEventListener('submit', function(event) {\r\n");
      out.write("              if (form.checkValidity() === false) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                event.stopPropagation();\r\n");
      out.write("              }\r\n");
      out.write("              form.classList.add('was-validated');\r\n");
      out.write("            }, false);\r\n");
      out.write("          });\r\n");
      out.write("        }, false);\r\n");
      out.write("      })();\r\n");
      out.write("      </script>\r\n");
      out.write("     <script>\r\n");
      out.write("    \r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#login').validate({\r\n");
      out.write("\t\t    rules: {\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t        email: {\r\n");
      out.write("\t\t        \tminlength: 5,\r\n");
      out.write("\t\t        \tmaxlength: 200,\r\n");
      out.write("\t\t            email: true\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    errorElement: 'span',\r\n");
      out.write("\t        highlight: function(element, errorClass, validClass) {\r\n");
      out.write("\t            $(element).removeClass(validClass);\r\n");
      out.write("\t            $(\"#togglePassword\").hide();\r\n");
      out.write("\t        },\r\n");
      out.write("\t        unhighlight: function(element, errorClass, validClass) {\r\n");
      out.write("\t            $(element).addClass(validClass);\r\n");
      out.write("\t            $(\"#togglePassword\").show();\r\n");
      out.write("\t        },\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function showPassword() {\r\n");
      out.write("\t  var x = document.getElementById(\"Password\");\r\n");
      out.write("\t  if (x.type === \"password\") {\r\n");
      out.write("\t    x.type = \"text\";\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t    x.type = \"password\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
